# Generated by Django 4.2.7 on 2025-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_referee',
            field=models.BooleanField(default=False),
        ),
    ]
